# Generated by Django 3.0.2 on 2020-02-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speed', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('evolutions', models.ManyToManyField(related_name='_pokemon_evolutions_+', to='pokedex.Pokemon')),
            ],
        ),
    ]
