# Generated by Django 3.0.2 on 2020-02-05 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolutions',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pre_evolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='pokedex.Pokemon'),
        ),
    ]
